language: swift

osx_image: xcode11.3

env:
  - SCHEME="Tea-Package" DESTINATION="platform=OS X,arch=x86_64" SDK=macosx PLATFORM="OSX"

script:
  - swift package generate-xcodeproj --enable-code-coverage
  - xcodebuild clean build -project Tea.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test
  - xcodebuild test -project Tea.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test 

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never